'use client'

import CitySearchBar from '@/components/CitySearchBar/CitySearchBar';
import Header from '@/components/Header/Header'
import { QueryClient, QueryClientProvider } from 'react-query'
import '@/styles/global.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body>
          <Header />
          <CitySearchBar />
          <main className={`p-2 flex justify-center items-center flex-grow w-full h-full`}>
            <div className="page__container h-full w-full flex flex-grow">
              {children}
            </div>
          </main>
        </body>
      </QueryClientProvider>
    </html>
  )
}
